# Generated by Django 5.2.5 on 2025-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('resnet50', 'ResNet-50 v2.1'), ('efficientnet', 'EfficientNet-B0'), ('mobilenet', 'MobileNet v2'), ('vgg16', 'VGG-16'), ('custom', 'カスタムモデル')], max_length=50, verbose_name='モデル名')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='バージョン')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用可能')),
                ('description', models.TextField(help_text='モデルの特徴や用途について説明', verbose_name='モデル説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '機械学習モデル',
                'verbose_name_plural': '機械学習モデル',
                'db_table': 'ml_models',
                'ordering': ['name', 'version'],
            },
        ),
    ]
