# Generated by Django 5.2.5 on 2025-09-03 01:10

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('resnet50', 'ResNet-50 v2.1'), ('efficientnet', 'EfficientNet-B0'), ('mobilenet', 'MobileNet v2'), ('vgg16', 'VGG-16'), ('custom', 'カスタムモデル')], max_length=50, verbose_name='モデル名')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='バージョン')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用可能')),
                ('description', models.TextField(help_text='モデルの特徴や用途について説明', verbose_name='モデル説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '機械学習モデル',
                'verbose_name_plural': '機械学習モデル',
                'db_table': 'ml_models',
                'ordering': ['name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='ユーザー名は英数字とアンダースコアのみ使用できます', regex='^[a-zA-Z0-9_]+$')], verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='メールアドレス')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理者権限')),
                ('is_active', models.BooleanField(default=True, verbose_name='アカウント有効性')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイル保存パス')),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='サムネイル画像パス')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('status', models.CharField(choices=[('preparing', '準備中'), ('analyzing', '解析中'), ('success', '解析成功'), ('failed', '失敗')], default='preparing', max_length=20, verbose_name='ステータス')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='エラーログ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='アップロードユーザー')),
                ('model_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_analyzer.mlmodel', verbose_name='使用モデル')),
            ],
            options={
                'verbose_name': '画像',
                'verbose_name_plural': '画像',
                'db_table': 'images',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='解析されたラベル')),
                ('confidence', models.DecimalField(decimal_places=2, help_text='0.00〜100.00%の範囲', max_digits=5, verbose_name='信頼度')),
                ('model_version', models.CharField(help_text='解析に使用したモデルのバージョン', max_length=20, verbose_name='モデルバージョン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='解析実行日時')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='image_analyzer.image', verbose_name='画像')),
            ],
            options={
                'verbose_name': '解析結果',
                'verbose_name_plural': '解析結果',
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, help_text='0.00〜100.00の範囲', max_digits=5, verbose_name='進捗率')),
                ('current_stage', models.CharField(choices=[('preprocessing', '前処理'), ('model_execution', 'モデル実行'), ('postprocessing', '後処理'), ('completed', '完了')], max_length=20, verbose_name='現在の段階')),
                ('stage_description', models.TextField(blank=True, null=True, verbose_name='段階の詳細説明')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='ログ記録時刻')),
                ('estimated_completion', models.DateTimeField(blank=True, null=True, verbose_name='推定完了時刻')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='image_analyzer.image', verbose_name='画像')),
            ],
            options={
                'verbose_name': '進捗ログ',
                'verbose_name_plural': '進捗ログ',
                'db_table': 'progress_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TimelineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_started_at', models.DateTimeField(blank=True, null=True, verbose_name='アップロード開始時刻')),
                ('upload_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='アップロード完了時刻')),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True, verbose_name='解析開始時刻')),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析完了時刻')),
                ('model_used', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用モデル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_log', to='image_analyzer.image', verbose_name='画像')),
            ],
            options={
                'verbose_name': 'タイムラインログ',
                'verbose_name_plural': 'タイムラインログ',
                'db_table': 'timeline_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
