# Generated by Django 5.2.5 on 2025-08-30 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイル保存パス')),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='サムネイル画像パス')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('status', models.CharField(choices=[('preparing', '準備中'), ('analyzing', '解析中'), ('success', '解析成功'), ('failed', '失敗')], default='preparing', max_length=20, verbose_name='ステータス')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='エラーログ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('model_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_analyzer.mlmodel', verbose_name='使用モデル')),
            ],
            options={
                'verbose_name': '画像',
                'verbose_name_plural': '画像',
                'db_table': 'images',
                'ordering': ['-upload_date'],
            },
        ),
    ]
