# Generated by Django 5.2.5 on 2025-08-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, help_text='0.00〜100.00の範囲', max_digits=5, verbose_name='進捗率')),
                ('current_stage', models.CharField(choices=[('preprocessing', '前処理'), ('model_execution', 'モデル実行'), ('postprocessing', '後処理'), ('completed', '完了')], max_length=20, verbose_name='現在の段階')),
                ('stage_description', models.TextField(blank=True, null=True, verbose_name='段階の詳細説明')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='ログ記録時刻')),
                ('estimated_completion', models.DateTimeField(blank=True, null=True, verbose_name='推定完了時刻')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='image_analyzer.image', verbose_name='画像')),
            ],
            options={
                'verbose_name': '進捗ログ',
                'verbose_name_plural': '進捗ログ',
                'db_table': 'progress_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
