# Generated by Django 5.2.5 on 2025-09-03 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0002_remove_image_user_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='キュー位置')),
                ('status', models.CharField(choices=[('waiting', '待機中'), ('processing', '処理中'), ('completed', '完了'), ('failed', '失敗'), ('cancelled', 'キャンセル')], default='waiting', max_length=20, verbose_name='キュー状態')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '通常'), ('high', '高'), ('urgent', '緊急')], default='normal', max_length=10, verbose_name='優先度')),
                ('queued_at', models.DateTimeField(auto_now_add=True, verbose_name='キュー追加日時')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='処理開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理完了日時')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='リトライ回数')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='使用モデル')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='image_analyzer.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '解析キュー',
                'verbose_name_plural': '解析キュー',
                'db_table': 'analysis_queue',
                'ordering': ['priority', 'position', 'queued_at'],
            },
        ),
    ]
