# Generated by Django 5.2.5 on 2025-08-30 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0003_progresslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='解析されたラベル')),
                ('confidence', models.DecimalField(decimal_places=2, help_text='0.00〜100.00%の範囲', max_digits=5, verbose_name='信頼度')),
                ('model_version', models.CharField(help_text='解析に使用したモデルのバージョン', max_length=20, verbose_name='モデルバージョン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='解析実行日時')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='image_analyzer.image', verbose_name='画像')),
            ],
            options={
                'verbose_name': '解析結果',
                'verbose_name_plural': '解析結果',
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
