# Generated by Django 5.2.5 on 2025-09-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0003_remove_image_user_analysisqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(
                default=21,  # 既存のユーザーIDをデフォルトに設定
                on_delete=django.db.models.deletion.CASCADE,
                to='image_analyzer.user',
                verbose_name='アップロードユーザー',
                related_name='uploaded_images'
            ),
            preserve_default=False,
        ),
    ]
