# Generated by Django 5.2.5 on 2025-09-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0004_auto_20250903_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('uploaded', 'アップロード完了'), ('preparing', '準備中'), ('analyzing', '解析中'), ('success', '解析成功'), ('failed', '失敗')], default='preparing', max_length=20, verbose_name='ステータス'),
        ),
    ]
