# Generated by Django 5.2.5 on 2025-09-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0004_analysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_started_at', models.DateTimeField(blank=True, null=True, verbose_name='アップロード開始時刻')),
                ('upload_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='アップロード完了時刻')),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True, verbose_name='解析開始時刻')),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析完了時刻')),
                ('model_used', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用モデル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_log', to='image_analyzer.image', verbose_name='画像')),
            ],
            options={
                'verbose_name': 'タイムラインログ',
                'verbose_name_plural': 'タイムラインログ',
                'db_table': 'timeline_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
