# Generated by Django 5.2.5 on 2025-09-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0005_alter_image_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='model_name',
            field=models.CharField(default='resnet50', help_text='解析に使用したモデルの名前', max_length=50, verbose_name='使用モデル名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='rank',
            field=models.PositiveIntegerField(default=1, help_text='予測結果の順位（1位、2位など）', verbose_name='順位'),
            preserve_default=False,
        ),
    ]
