# Generated by Django 5.2.6 on 2025-09-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0006_analysisresult_model_name_analysisresult_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinelog',
            name='upload_step_color',
            field=models.CharField(blank=True, default='success', max_length=20, verbose_name='アップロード完了色'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='upload_step_description',
            field=models.CharField(blank=True, default='ファイルのアップロードに成功しました', max_length=200, verbose_name='アップロード完了説明'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='upload_step_icon',
            field=models.CharField(blank=True, default='check-circle', max_length=50, verbose_name='アップロード完了アイコン'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='upload_step_status',
            field=models.CharField(blank=True, default='アップロード成功', max_length=50, verbose_name='アップロード完了ステータス'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='upload_step_title',
            field=models.CharField(blank=True, default='ファイルアップロード完了', max_length=100, verbose_name='アップロード完了タイトル'),
        ),
    ]
