# Generated by Django 5.2.6 on 2025-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0007_timelinelog_upload_step_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinelog',
            name='analysis_progress_percentage',
            field=models.IntegerField(blank=True, default=0, verbose_name='解析進捗率'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='analysis_progress_stage',
            field=models.CharField(blank=True, default='preparing', max_length=50, verbose_name='解析進捗ステージ'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='analysis_step_color',
            field=models.CharField(blank=True, default='warning', max_length=20, verbose_name='解析ステップ色'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='analysis_step_description',
            field=models.CharField(blank=True, default='AIによる画像解析を開始しました。', max_length=200, verbose_name='解析ステップ説明'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='analysis_step_icon',
            field=models.CharField(blank=True, default='brain', max_length=50, verbose_name='解析ステップアイコン'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='analysis_step_status',
            field=models.CharField(blank=True, default='解析中', max_length=50, verbose_name='解析ステップステータス'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='analysis_step_title',
            field=models.CharField(blank=True, default='解析開始', max_length=100, verbose_name='解析ステップタイトル'),
        ),
    ]
