# Generated by Django 5.2.6 on 2025-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0008_timelinelog_analysis_progress_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinelog',
            name='completion_step_color',
            field=models.CharField(blank=True, default='success', max_length=20, verbose_name='完了ステップ色'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='completion_step_description',
            field=models.CharField(blank=True, default='画像のカテゴリー分類が完了しました', max_length=200, verbose_name='完了ステップ説明'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='completion_step_icon',
            field=models.CharField(blank=True, default='brain', max_length=50, verbose_name='完了ステップアイコン'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='completion_step_status',
            field=models.CharField(blank=True, default='完了', max_length=50, verbose_name='完了ステップステータス'),
        ),
        migrations.AddField(
            model_name='timelinelog',
            name='completion_step_title',
            field=models.CharField(blank=True, default='解析完了', max_length=100, verbose_name='完了ステップタイトル'),
        ),
    ]
