# Generated by Django 5.2.5 on 2025-09-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0009_timelinelog_completion_step_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinelog',
            name='analysis_step_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='解析ステップ説明'),
        ),
        migrations.AlterField(
            model_name='timelinelog',
            name='analysis_step_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='解析ステップステータス'),
        ),
        migrations.AlterField(
            model_name='timelinelog',
            name='analysis_step_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='解析ステップタイトル'),
        ),
        migrations.AlterField(
            model_name='timelinelog',
            name='completion_step_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='完了ステップ説明'),
        ),
        migrations.AlterField(
            model_name='timelinelog',
            name='completion_step_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='完了ステップステータス'),
        ),
        migrations.AlterField(
            model_name='timelinelog',
            name='completion_step_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='完了ステップタイトル'),
        ),
    ]
