# Generated by Django 5.2.5 on 2025-09-22 04:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0010_fix_timeline_log_null_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('upload', 'アップロード'), ('uploaded', 'アップロード完了'), ('preparing', '準備中'), ('analyzing', '解析中'), ('success', '解析成功'), ('failed', '失敗')], default='preparing', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='name',
            field=models.CharField(choices=[('resnet50', 'ResNet-50 v2.1'), ('efficientnet', 'EfficientNet-B0'), ('mobilenet', 'MobileNet v2'), ('vgg16', 'VGG-16'), ('clip', 'CLIP'), ('custom', 'カスタムモデル')], max_length=50, verbose_name='モデル名'),
        ),
        migrations.CreateModel(
            name='TransUploadedImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, verbose_name='画像ID')),
                ('filename', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイルパス')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='アップロード日時')),
                ('status', models.CharField(choices=[('preparing', '準備中'), ('analyzing', '解析中'), ('success', '解析成功'), ('failed', '失敗')], default='preparing', max_length=20, verbose_name='ステータス')),
                ('upload_error', models.TextField(blank=True, null=True, verbose_name='アップロードエラー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images_new', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '画像アップロード',
                'verbose_name_plural': '画像アップロード',
                'db_table': 'trans_uploaded_image',
                'ordering': ['-upload_date'],
            },
        ),
    ]
