# Generated by Django 5.2.5 on 2025-09-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0011_alter_image_status_alter_mlmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transuploadedimage',
            name='upload_error',
        ),
    ]
