# Generated by Django 5.2.6 on 2025-09-29 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0012_remove_transuploadedimage_upload_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisqueue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='image_analyzer.user'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='image_analyzer.user'),
        ),
        migrations.AlterField(
            model_name='transuploadedimage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images_new', to='image_analyzer.user', verbose_name='ユーザーID'),
        ),
    ]
