# Generated by Django 5.2.5 on 2025-09-22 04:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理者権限')),
                ('is_active', models.BooleanField(default=True, verbose_name='アカウント有効性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ユーザーマスタ',
                'verbose_name_plural': 'ユーザーマスタ',
                'db_table': 'mst_user_v2',
            },
        ),
        migrations.CreateModel(
            name='TransUploadedImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, verbose_name='画像ID')),
                ('filename', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイルパス')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='アップロード日時')),
                ('status', models.CharField(choices=[('preparing', '準備中'), ('analyzing', '解析中'), ('success', '解析成功'), ('failed', '失敗')], default='preparing', max_length=20, verbose_name='ステータス')),
                ('upload_error', models.TextField(blank=True, null=True, verbose_name='アップロードエラー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='new_image_analyzer_v2.mstuser', verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '画像アップロード',
                'verbose_name_plural': '画像アップロード',
                'db_table': 'trans_uploaded_image_v2',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='TransImageAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='解析ID')),
                ('label', models.CharField(max_length=100, verbose_name='分類ラベル')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='信頼度')),
                ('model_name', models.CharField(max_length=50, verbose_name='モデル名')),
                ('rank', models.PositiveIntegerField(verbose_name='順位')),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True, verbose_name='解析開始時刻')),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析完了時刻')),
                ('analysis_error', models.TextField(blank=True, null=True, verbose_name='解析エラー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('image_id', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='new_image_analyzer_v2.transuploadedimage', verbose_name='画像ID')),
            ],
            options={
                'verbose_name': '画像解析結果',
                'verbose_name_plural': '画像解析結果',
                'db_table': 'trans_image_analysis_v2',
                'ordering': ['image_id', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='TransAnalysisTimeline',
            fields=[
                ('timeline_id', models.AutoField(primary_key=True, serialize=False, verbose_name='タイムラインID')),
                ('analysis_status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '解析中'), ('completed', '解析完了'), ('failed', '解析失敗')], default='not_started', max_length=20, verbose_name='解析状態')),
                ('previous_results', models.CharField(blank=True, max_length=200, null=True, verbose_name='前回解析結果')),
                ('image_id', models.OneToOneField(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_log', to='new_image_analyzer_v2.transuploadedimage', verbose_name='画像ID')),
            ],
            options={
                'verbose_name': '解析ログ',
                'verbose_name_plural': '解析ログ',
                'db_table': 'trans_analysis_timeline_v2',
            },
        ),
    ]
