# Generated by Django 5.2.5 on 2025-09-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transuploadedimage',
            name='status',
            field=models.CharField(choices=[('preparing', '準備中'), ('analyzing', '解析中'), ('success', '解析成功'), ('failed', '失敗')], default='uploaded', max_length=20, verbose_name='ステータス'),
        ),
    ]
