# Generated by Django 5.2.5 on 2025-09-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0002_alter_transuploadedimage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transuploadedimage',
            name='upload_error',
        ),
    ]
