# Generated by Django 5.2.5 on 2025-09-26 03:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0003_remove_transuploadedimage_upload_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='transuploadedimage',
            name='analysis_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解析完了時刻'),
        ),
        migrations.AddField(
            model_name='transuploadedimage',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解析開始時刻'),
        ),
        migrations.AddField(
            model_name='transuploadedimage',
            name='upload_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='アップロード完了時刻'),
        ),
        migrations.AddField(
            model_name='transuploadedimage',
            name='upload_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='アップロード開始時刻'),
        ),
        migrations.AlterField(
            model_name='transuploadedimage',
            name='status',
            field=models.CharField(choices=[('uploading', 'アップロード中'), ('uploaded', 'アップロード完了'), ('analyzing', '解析中'), ('completed', '解析完了'), ('failed', '解析失敗')], default='uploading', max_length=20, verbose_name='ステータス'),
        ),
        migrations.DeleteModel(
            name='TransAnalysisTimeline',
        ),
    ]
