# Generated by Django 5.2.6 on 2025-09-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0004_transuploadedimage_analysis_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transuploadedimage',
            name='analysis_completed_at',
        ),
        migrations.RemoveField(
            model_name='transuploadedimage',
            name='analysis_started_at',
        ),
    ]
