# Generated by Django 5.2.6 on 2025-09-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0005_remove_transuploadedimage_analysis_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transuploadedimage',
            name='upload_started_at',
        ),
    ]
