# Generated by Django 5.2.6 on 2025-09-26 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0006_remove_transuploadedimage_upload_started_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transuploadedimage',
            options={'ordering': ['-upload_started_at'], 'verbose_name': '画像アップロード', 'verbose_name_plural': '画像アップロード'},
        ),
        migrations.RemoveField(
            model_name='transuploadedimage',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='transuploadedimage',
            name='upload_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='アップロード開始時刻'),
        ),
    ]
