# Generated by Django 5.2.6 on 2025-09-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0007_alter_transuploadedimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transimageanalysis',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transuploadedimage',
            name='created_at',
        ),
    ]
