# Generated by Django 5.2.5 on 2025-09-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0008_remove_transimageanalysis_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transimageanalysis',
            name='created_at',
        ),
    ]
