# Generated by Django 5.2.6 on 2025-09-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0009_remove_transimageanalysis_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transuploadedimage',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解析開始時刻'),
        ),
    ]
