# Generated by Django 5.2.6 on 2025-09-27 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0011_transuploadedimage_analysis_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transuploadedimage',
            name='analysis_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='解析開始時刻'),
        ),
    ]
