# Generated by Django 5.2.6 on 2025-09-29 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0013_make_transimageanalysis_analysis_started_at_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transuploadedimage',
            options={'ordering': ['-created_at'], 'verbose_name': '画像アップロード', 'verbose_name_plural': '画像アップロード'},
        ),
        migrations.RemoveField(
            model_name='transuploadedimage',
            name='upload_completed_at',
        ),
        migrations.RemoveField(
            model_name='transuploadedimage',
            name='upload_started_at',
        ),
        migrations.AddField(
            model_name='transuploadedimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='アップロード日時'),
        ),
        migrations.AlterField(
            model_name='transuploadedimage',
            name='status',
            field=models.CharField(choices=[('uploading', 'アップロード中'), ('uploaded', 'アップロード完了'), ('analyzing', '解析中'), ('completed', '解析完了'), ('failed', '解析失敗')], default='analyzing', max_length=20, verbose_name='ステータス'),
        ),
    ]
