# Generated by Django 5.2.6 on 2025-09-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0014_simplify_upload_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transuploadedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時'),
        ),
    ]
