# Generated by Django 5.2.6 on 2025-09-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0015_fix_created_at_auto_now_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$dummy$dummy', max_length=128, verbose_name='パスワード'),
        ),
    ]
