# Generated by Django 5.2.6 on 2025-09-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0016_mstuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mstuser',
            name='updated_at',
        ),
    ]
