# Generated by Django 5.2.5 on 2025-09-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0017_remove_mstuser_created_at_remove_mstuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transuploadedimage',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解析開始時刻'),
        ),
    ]
