# Generated by Django 5.2.5 on 2025-09-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image_analyzer_v2', '0018_alter_transuploadedimage_analysis_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transuploadedimage',
            name='upload_order',
            field=models.IntegerField(default=0, help_text='ユーザーごとのアップロード順序（1から始まる連番）', verbose_name='アップロード順序'),
        ),
    ]
